package org.mln.enums;

public enum ConfigProperties {

    APPNAME,
    URL,
    OVERRIDEDYNAMICREPORT,
    PASSEDSTEPSSCREENSHOT,
    FAILEDSTEPSSCREENSHOT,
    SKIPPEDSTEPSSCREENSHOT,

    RETRYFAILEDTEST

}
